<?php

return [
    'characters' => [
        [
            'full_name' => 'Aldric Stormbringer',
            'race' => 'Human',
            'img' => '',
            'sex' => 'Male',
            'age' => '35',
            'alignment' => 'Chaotic Good',
            'health_points' => '85',
            'class' => 'Warrior',
            'sub_class' => 'Berserker',
            'level' => '10',
            'armour_class' => '18',
            'cd' => '15',
            'backstory' => 'Aldric, once a simple blacksmith, found his true calling on the battlefield after his village was razed by bandits.'
        ],
        [
            'full_name' => 'Lyra Moonshadow',
            'race' => 'Elf',
            'img' => '',
            'sex' => 'Female',
            'age' => '120',
            'alignment' => 'Neutral',
            'health_points' => '70',
            'class' => 'Rogue',
            'sub_class' => 'Assassin',
            'level' => '8',
            'armour_class' => '16',
            'cd' => '18',
            'backstory' => 'Lyra grew up in the shadows of the elven forests, mastering the art of stealth and precision.'
        ],
        [
            'full_name' => 'Thorin Ironfist',
            'race' => 'Dwarf',
            'img' => '',
            'sex' => 'Male',
            'age' => '150',
            'alignment' => 'Lawful Good',
            'health_points' => '95',
            'class' => 'Paladin',
            'sub_class' => 'Oathkeeper',
            'level' => '12',
            'armour_class' => '20',
            'cd' => '17',
            'backstory' => 'Thorin is a devout warrior who defends the weak and upholds justice in the name of his deity.'
        ],
        [
            'full_name' => 'Eldrin Starfire',
            'race' => 'Half-Elf',
            'img' => '',
            'sex' => 'Male',
            'age' => '80',
            'alignment' => 'Chaotic Neutral',
            'health_points' => '60',
            'class' => 'Wizard',
            'sub_class' => 'Elementalist',
            'level' => '9',
            'armour_class' => '14',
            'cd' => '20',
            'backstory' => 'Eldrin has always been fascinated by the raw power of the elements and has dedicated his life to mastering them.'
        ],
        [
            'full_name' => 'Mira Lightweaver',
            'race' => 'Human',
            'img' => '',
            'sex' => 'Female',
            'age' => '28',
            'alignment' => 'Neutral Good',
            'health_points' => '65',
            'class' => 'Cleric',
            'sub_class' => 'Healer',
            'level' => '7',
            'armour_class' => '15',
            'cd' => '19',
            'backstory' => 'Mira serves as a beacon of hope and healing, traveling the land to aid those in need.'
        ],
        [
            'full_name' => 'Gorak Stonecrusher',
            'race' => 'Orc',
            'img' => '',
            'sex' => 'Male',
            'age' => '40',
            'alignment' => 'Neutral Evil',
            'health_points' => '100',
            'class' => 'Barbarian',
            'sub_class' => 'Warlord',
            'level' => '11',
            'armour_class' => '17',
            'cd' => '14',
            'backstory' => 'Gorak thrives on the chaos of battle, leading his clan with an iron fist and unmatched strength.'
        ],
        [
            'full_name' => 'Seraphina Dawnstrider',
            'race' => 'Tiefling',
            'img' => '',
            'sex' => 'Female',
            'age' => '25',
            'alignment' => 'Lawful Neutral',
            'health_points' => '55',
            'class' => 'Sorcerer',
            'sub_class' => 'Wild Magic',
            'level' => '6',
            'armour_class' => '13',
            'cd' => '21',
            'backstory' => 'Seraphina\'s innate magical abilities have always set her apart, making her both feared and revered.'
        ],
        [
            'full_name' => 'Darin Swiftfoot',
            'race' => 'Halfling',
            'img' => '',
            'sex' => 'Male',
            'age' => '50',
            'alignment' => 'Chaotic Good',
            'health_points' => '45',
            'class' => 'Bard',
            'sub_class' => 'Lorekeeper',
            'level' => '5',
            'armour_class' => '14',
            'cd' => '16',
            'backstory' => 'Darin travels from town to town, collecting stories and spreading joy through his music and tales.'
        ],
        [
            'full_name' => 'Kara Stormwind',
            'race' => 'Human',
            'img' => '',
            'sex' => 'Female',
            'age' => '30',
            'alignment' => 'Neutral Good',
            'health_points' => '80',
            'class' => 'Monk',
            'sub_class' => 'Way of the Open Hand',
            'level' => '9',
            'armour_class' => '18',
            'cd' => '17',
            'backstory' => 'Kara seeks balance in all things and has trained her body and mind to achieve inner peace and external harmony.'
        ],
        [
            'full_name' => 'Ragnar Thunderfist',
            'race' => 'Half-Orc',
            'img' => '',
            'sex' => 'Male',
            'age' => '38',
            'alignment' => 'Neutral',
            'health_points' => '90',
            'class' => 'Fighter',
            'sub_class' => 'Champion',
            'level' => '10',
            'armour_class' => '19',
            'cd' => '15',
            'backstory' => 'Ragnar is a fearsome warrior who lives for the thrill of combat, honing his skills to become the ultimate champion.'
        ]
    ]
];
